<a href="https://colab.research.google.com/github/19PA1A0495/Python-Basics/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [6]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
a=np.arange(15).reshape(5,3)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [10]:
a.shape

(5, 3)

In [11]:
a.ndim

2

In [12]:
a.dtype

dtype('int64')

In [13]:
a.itemsize

8

In [2]:
import numpy as np
a=np.arange(15).reshape(5,3)
type(a)

numpy.ndarray

numpy.ndarray

In [3]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
np.ones((3,4),dtype=np.int64)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [6]:
np.empty((3,4))

array([[0.00000000e+000, 2.51973479e-322, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 1.16095484e-028, 7.52736939e+252,
        2.86750350e+161],
       [1.44506353e+214, 2.28176682e+243, 9.96124223e-143,
        4.05449735e-317]])

In [9]:
np.eye(4,dtype=np.int64)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [10]:
np.full((3,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [14]:
a=np.random.random((1,2))
a

array([[0.14875428, 0.59806678]])

In [18]:
a=np.array([10,20,30,40])
b=np.arange(4)
print(a)
print(b)
c=a+b
print(c)
print(a**2)
print(b>3)
a[1]+=5
print(a)
print(a*b)
print(10*np.sin(a))

[10 20 30 40]
[0 1 2 3]
[10 21 32 43]
[ 100  400  900 1600]
[False False False False]
[10 25 30 40]
[  0  25  60 120]
[-5.44021111 -1.3235175  -9.88031624  7.4511316 ]


In [20]:
a=np.array([[1,4],[2,3]])
b=np.array([[4,5],[6,7]])
print(a)
print(b)
print(a*b)
print(a@b)
print(a.dot(b))
print(np.dot(a,b))

[[1 4]
 [2 3]]
[[4 5]
 [6 7]]
[[ 4 20]
 [12 21]]
[[28 33]
 [26 31]]
[[28 33]
 [26 31]]
[[28 33]
 [26 31]]


In [21]:
a=np.arange(10).reshape(2,5)
print(a)
print(a.sum())
print(a.sum(axis=0))
print(a.sum(axis=1))
print(a.min(axis=1))
print(a.max(axis=1))
print(a.min(axis=0))
print(a.max(axis=0))

[[0 1 2 3 4]
 [5 6 7 8 9]]
45
[ 5  7  9 11 13]
[10 35]
[0 5]
[4 9]
[0 1 2 3 4]
[5 6 7 8 9]


In [27]:
x=np.arange(4)**2
print(x)
print(x[2:3])
print(x[-1: ])
print(x[1:2])
print(x[1])

[0 1 4 9]
[4]
[9]
[1]
1


In [28]:
a=np.arange(12).reshape(3,4)
print(a)
print(a[1:3])
print(a[1:3,1:2])
print(a[2,])
print(a[:2],)
print(a[:3,])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 4  5  6  7]
 [ 8  9 10 11]]
[[5]
 [9]]
[ 8  9 10 11]
[[0 1 2 3]
 [4 5 6 7]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [33]:
n=np.arange(10).reshape(2,5)
print(n)
print(n[-2,-3])
print(n[-1,-1])

[[0 1 2 3 4]
 [5 6 7 8 9]]
2
9


In [34]:
a=np.arange(12).reshape(3,4)
for i in a:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [35]:
a=np.arange(15).reshape(5,3)
for i in a.flat:
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
